POST http://localhost:3001/api/execute
Content-Type: application/json

{
    "sql": "SELECT * FROM empresa.clientes;"
}

###

GET http://localhost:3001/api/schema
Content-Type: application/json


###

POST http://localhost:3001/api/execute
Content-Type: application/json

{
    "sql": "SELECT * FROM empresa.clientes;"
}


 